[package]
name = "pyrust_xlsxwriter"
version = "0.1.0"
edition = "2021"

[lib]
name = "pyrust_xlsxwriter"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.25.0"
rust_xlsxwriter = "0.89.1"
csv = "1.3.1"
tempfile = "3.20.0"
