[package]
name = "pyrust_xlsxwriter"
version = "0.1.0"
edition = "2021"

[lib]
name = "pyrust_xlsxwriter"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.21.2"
rust_xlsxwriter = "0.64.2"
csv = "1.1.6"
tempfile = "3.10.1"
