name: Build pyrust_xlsxwriter wheels for Linux

on:
  pull_request:
    paths:
      - 'rust/pyrust_xlsxwriter/**'
      - '.github/workflows/build-linux-wheels.yml'
  push:
    branches:
      - 'main'
  workflow_dispatch:
  schedule:
    - cron: '8 05 * * *'

permissions:
  contents: read

jobs:
  build-linux-wheels:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [ '3.10', '3.11', '3.12', '3.13' ]

    env:
      rust_build_directory: rust/pyrust_xlsxwriter

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install maturin
      run: pip install maturin

    - name: Build pyrust_xlsxwriter
      run: maturin build --release --cargo-extra-args="--no-default-features"
      working-directory: ${{ env.rust_build_directory }}

    - name: Run Rust unit tests
      run: cargo test --all --no-default-features
      working-directory: ${{ env.rust_build_directory }}

    - name: Upload wheel
      uses: actions/upload-artifact@v4
      with:
        name: pyrust_xlsxwriter-python-${{ matrix.python-version }}-linux-wheel
        path: ${{ env.rust_build_directory }}/target/wheels/pyrust_xlsxwriter-*.whl